spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:temperature-db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
server:
  port: 9092

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

temperature-stats:
  swagger:
    title: Temperature statistics service
    description: Service for temperature sensors statistics
    licenseUrl: https://opensource.org/licenses/Apache-2.0
    contactName: Dmytro Karmanov
    contactUrl: http://github.com/karmanov/temperature-statistics-service
    contactEmail: karmanov.d@gmail.com
    license: Apache-2.0
    version: 0.0.1-SNAPSHOT
